# Generated by Django 6.0.2 on 2026-07-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Local image upload. Takes precedence over image_url.', null=True, upload_to='equipment/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image_url',
            field=models.URLField(blank=True, help_text='Remote image URL (used if no file is uploaded).'),
        ),
    ]
